### PR TITLE
MQueue: send and receive `ByteString`

### PR DESCRIPTION
**Pull request by magthe**
I think it makes more sense to send and receive `ByteString`s rather than `String`s.

Since this is an API change I suppose a version bump might be required too.  The API for sending and receiving is still slightly awkward, but it's close to the C API, which I guess has a point.  More "natural" APIs can always be layered above.

### CODE REVIEW

**Comment by magthe** [comment]
I didn't mean to include the change to using stack to build on TravisCI.  Feel free to disregard that change.

**Comment by mgajda** [comment]
Thank you very much for the patch!

**Comment by magthe** [comment]
Any chance of getting an official release on Hackage?

**Comment by mgajda** [comment]
oh, yes! this evening sgt?

On Tuesday, 24 November 2015, Magnus Therning notifications@github.com
wrote:

> Any chance of getting an official release on Hackage?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mgajda/posix-realtime/pull/4#issuecomment-159204297.

## 

  Pozdrawiam
    Michał

**Comment by magthe** [comment]
I'm not in the military ;)  I'm in no rush at all, so evening time in S'pore is just fine :)

**Comment by mgajda** [comment]
It may make another day Magnus, since I tried to combine our test
matrices. That would give us hope that it is consistent both with Stack
(which is way easier) and stock GHC at all times.

## So no cheating with unit tests before release!!!

  Cheers
    Michal

**Comment by mgajda** [comment]
By the way, is it not better to use Text instead of ByteString?

**Comment by magthe** [comment]
The API doesn't impose, or assume, any particular structure of the messages, so it's best to treat them as sequences of bytes, i.e. `ByteString`.

http://linux.die.net/man/7/mq_overview

**Pull request merged**
